import type {
  Trip,
  Person,
  CostGroup,
  Expense,
  Prepayment,
  GroupMember,
  SettlementStatus,
  TripBundle,
} from "../shared/types.ts";
import { computeGroupSummaries, computePaysheet, travelReimbursement, type EngineInput } from "./engine.ts";

export async function loadEngineInput(db: D1Database, tripId: number): Promise<EngineInput | null> {
  const trip = await db.prepare("SELECT * FROM trips WHERE id = ?").bind(tripId).first<Trip>();
  if (!trip) return null;

  const [people, groups, expenses, prepayments, members, travelDrivers, settlements] =
    await db.batch([
      db.prepare("SELECT * FROM people WHERE trip_id = ? ORDER BY type, name").bind(tripId),
      db.prepare("SELECT * FROM cost_groups WHERE trip_id = ? ORDER BY sort_order, id").bind(tripId),
      db.prepare("SELECT * FROM expenses WHERE trip_id = ? ORDER BY id").bind(tripId),
      db.prepare("SELECT * FROM prepayments WHERE trip_id = ? ORDER BY id").bind(tripId),
      db
        .prepare(
          "SELECT gm.* FROM group_members gm JOIN cost_groups g ON g.id = gm.group_id WHERE g.trip_id = ?",
        )
        .bind(tripId),
      db
        .prepare(
          "SELECT td.* FROM travel_drivers td JOIN cost_groups g ON g.id = td.group_id WHERE g.trip_id = ?",
        )
        .bind(tripId),
      db.prepare("SELECT person_id, status FROM settlements WHERE trip_id = ?").bind(tripId),
    ]);

  return {
    trip,
    people: people.results as Person[],
    groups: groups.results as CostGroup[],
    expenses: expenses.results as Expense[],
    prepayments: prepayments.results as Prepayment[],
    members: members.results as GroupMember[],
    travelDrivers: travelDrivers.results as { group_id: number; person_id: number }[],
    settlements: settlements.results as { person_id: number; status: SettlementStatus }[],
  };
}

export async function loadTripBundle(db: D1Database, tripId: number): Promise<TripBundle | null> {
  const input = await loadEngineInput(db, tripId);
  if (!input) return null;
  const groupSummaries = computeGroupSummaries(input);
  const paysheet = computePaysheet(input, groupSummaries);
  return {
    trip: input.trip,
    people: input.people,
    groups: input.groups,
    expenses: input.expenses,
    members: input.members,
    prepayments: input.prepayments,
    travelDrivers: input.travelDrivers,
    groupSummaries,
    paysheet,
  };
}

/**
 * Re-materialize the expenses generated by a travel group: one expense per
 * driver (payer = driver, amount = reimbursement) charged to the travel
 * group's cost_group_id. Keeps the paysheet in sync with travel inputs.
 */
export async function regenerateTravelExpenses(db: D1Database, groupId: number): Promise<void> {
  const group = await db.prepare("SELECT * FROM cost_groups WHERE id = ?").bind(groupId).first<CostGroup>();
  if (!group || group.kind !== "travel") return;
  const trip = await db.prepare("SELECT * FROM trips WHERE id = ?").bind(group.trip_id).first<Trip>();
  if (!trip) return;

  await db.prepare("DELETE FROM expenses WHERE source_travel_group_id = ?").bind(groupId).run();

  const target = group.cost_group_id ?? groupId;
  const amount = travelReimbursement(trip, group);
  if (amount <= 0) return;

  const drivers = await db
    .prepare("SELECT person_id FROM travel_drivers WHERE group_id = ?")
    .bind(groupId)
    .all<{ person_id: number }>();

  const stmts = drivers.results.map((d) =>
    db
      .prepare(
        "INSERT INTO expenses (trip_id, group_id, description, amount, payer_id, source_travel_group_id) VALUES (?, ?, ?, ?, ?, ?)",
      )
      .bind(trip.id, target, `Travel reimbursement: ${group.name}`, amount, d.person_id, groupId),
  );
  if (stmts.length) await db.batch(stmts);
}
