import type {
  Trip,
  Person,
  CostGroup,
  Expense,
  Prepayment,
  GroupMember,
  SettlementStatus,
  TripBundle,
} from "../shared/types.ts";
import { computeGroupSummaries, computePaysheet, travelReimbursement, type EngineInput } from "./engine.ts";
import { fetchRosterMember } from "./roster.ts";

/** Raw trip row: roster_units arrives as a JSON string from D1. */
type TripRow = Omit<Trip, "roster_units"> & { roster_units: string };

export function normalizeTrip(row: TripRow): Trip {
  let units: string[] = [];
  try {
    const v = JSON.parse(row.roster_units ?? "[]");
    if (Array.isArray(v)) units = v.filter((x): x is string => typeof x === "string");
  } catch {
    units = [];
  }
  return { ...row, roster_units: units };
}

export async function loadEngineInput(db: D1Database, tripId: number): Promise<EngineInput | null> {
  const row = await db.prepare("SELECT * FROM trips WHERE id = ?").bind(tripId).first<TripRow>();
  if (!row) return null;
  const trip = normalizeTrip(row);

  const [people, groups, expenses, prepayments, members, travelDrivers, settlements] =
    await db.batch([
      db.prepare("SELECT * FROM people WHERE trip_id = ? ORDER BY type, name").bind(tripId),
      db.prepare("SELECT * FROM cost_groups WHERE trip_id = ? ORDER BY sort_order, id").bind(tripId),
      db.prepare("SELECT * FROM expenses WHERE trip_id = ? ORDER BY id").bind(tripId),
      db.prepare("SELECT * FROM prepayments WHERE trip_id = ? ORDER BY id").bind(tripId),
      db
        .prepare(
          "SELECT gm.* FROM group_members gm JOIN cost_groups g ON g.id = gm.group_id WHERE g.trip_id = ?",
        )
        .bind(tripId),
      db
        .prepare(
          "SELECT td.* FROM travel_drivers td JOIN cost_groups g ON g.id = td.group_id WHERE g.trip_id = ?",
        )
        .bind(tripId),
      db.prepare("SELECT person_id, status FROM settlements WHERE trip_id = ?").bind(tripId),
    ]);

  return {
    trip,
    people: people.results as Person[],
    groups: groups.results as CostGroup[],
    expenses: expenses.results as Expense[],
    prepayments: prepayments.results as Prepayment[],
    members: members.results as GroupMember[],
    travelDrivers: travelDrivers.results as { group_id: number; person_id: number }[],
    settlements: settlements.results as { person_id: number; status: SettlementStatus }[],
  };
}

export async function loadTripBundle(db: D1Database, tripId: number): Promise<TripBundle | null> {
  const input = await loadEngineInput(db, tripId);
  if (!input) return null;
  const groupSummaries = computeGroupSummaries(input);
  const paysheet = computePaysheet(input, groupSummaries);
  return {
    trip: input.trip,
    people: input.people,
    groups: input.groups,
    expenses: input.expenses,
    members: input.members,
    prepayments: input.prepayments,
    travelDrivers: input.travelDrivers,
    groupSummaries,
    paysheet,
  };
}

/**
 * Re-materialize the expenses generated by a travel group: one expense per
 * driver (payer = driver, amount = reimbursement) charged to the travel
 * group's cost_group_id. Keeps the paysheet in sync with travel inputs.
 */
export async function regenerateTravelExpenses(db: D1Database, groupId: number): Promise<void> {
  const group = await db.prepare("SELECT * FROM cost_groups WHERE id = ?").bind(groupId).first<CostGroup>();
  if (!group || group.kind !== "travel") return;
  const trip = await db.prepare("SELECT * FROM trips WHERE id = ?").bind(group.trip_id).first<Trip>();
  if (!trip) return;

  await db.prepare("DELETE FROM expenses WHERE source_travel_group_id = ?").bind(groupId).run();

  const target = group.cost_group_id ?? groupId;
  const amount = travelReimbursement(trip, group);
  if (amount <= 0) return;

  const drivers = await db
    .prepare("SELECT person_id FROM travel_drivers WHERE group_id = ?")
    .bind(groupId)
    .all<{ person_id: number }>();

  const stmts = drivers.results.map((d) =>
    db
      .prepare(
        "INSERT INTO expenses (trip_id, group_id, description, amount, payer_id, source_travel_group_id) VALUES (?, ?, ?, ?, ?, ?)",
      )
      .bind(trip.id, target, `Travel reimbursement: ${group.name}`, amount, d.person_id, groupId),
  );
  if (stmts.length) await db.batch(stmts);
}

const last4 = (bsa: string) => bsa.slice(-4);

/**
 * Ensure a local projection row exists for a roster-db member, returning its
 * local people.id. Idempotent per (trip, bsa_number). For youth, the billable
 * guardian (relationships[0]) is projected first and linked as parent_id.
 * Throws if the bsa_number is not present in roster-db.
 */
export async function ensureLocalPerson(
  db: D1Database,
  roster: D1Database,
  tripId: number,
  bsa: string,
): Promise<number> {
  const existing = await db
    .prepare("SELECT id FROM people WHERE trip_id = ? AND bsa_number = ?")
    .bind(tripId, bsa)
    .first<{ id: number }>();
  if (existing) return existing.id;

  const member = await fetchRosterMember(roster, bsa);
  if (!member) throw new Error(`roster member ${bsa} not found`);

  let parentId: number | null = null;
  if (member.type === "scout" && member.guardian) {
    parentId = await ensureLocalPerson(db, roster, tripId, member.guardian.bsa_number);
  }

  await db
    .prepare(
      "INSERT INTO people (trip_id, name, code, email, type, parent_id, bsa_number, source) VALUES (?, ?, ?, ?, ?, ?, ?, 'roster') ON CONFLICT(trip_id, bsa_number) WHERE bsa_number IS NOT NULL DO NOTHING",
    )
    .bind(tripId, member.name, last4(bsa), member.email, member.type, parentId, bsa)
    .run();

  const row = await db
    .prepare("SELECT id FROM people WHERE trip_id = ? AND bsa_number = ?")
    .bind(tripId, bsa)
    .first<{ id: number }>();
  if (!row) throw new Error(`failed to project roster member ${bsa}`);
  return row.id;
}

/**
 * Resolve a person reference to a local people.id.
 *   "id:123"        -> existing local person 123
 *   "bsa:14140573"  -> roster member, projected in if needed
 */
export async function resolveRef(
  db: D1Database,
  roster: D1Database,
  tripId: number,
  ref: string,
): Promise<number> {
  if (ref.startsWith("bsa:")) {
    return ensureLocalPerson(db, roster, tripId, ref.slice(4));
  }
  if (ref.startsWith("id:")) {
    return Number(ref.slice(3));
  }
  // Bare number => treat as local id (back-compat).
  const n = Number(ref);
  if (Number.isFinite(n)) return n;
  throw new Error(`unrecognized person ref: ${ref}`);
}
